[package]
authors = ["Per Lindgren <per.lindgren@ltu.se>", "Jorge Aparicio <jorge@japaric.io>"]
categories = ["concurrency", "embedded", "no-std"]
description = "Parser of the app! macro used by the Real Time for The Masses (RTFM) framework"
documentation = "https://docs.rs/rtfm-syntax"
keywords = []
license = "MIT OR Apache-2.0"
name = "rtfm-syntax"
repository = "https://github.com/japaric/rtfm-syntax"
version = "0.2.1"

[dependencies]
error-chain = "0.10.0"
either = "1.4.0"
quote = "0.4.2"

[dependencies.syn]
version = "0.12.14"
features = ["full", "extra-traits"]

[dependencies.proc-macro2]
features = ["nightly"]
version = "0.2.2"

